### ISSUE TITLE
Com Port Error

### ISSUE THREAD

**Issue by annonch** [annonch/DSSnet#1]
When I try to run file `python powerCoord.py --trace 1 -et 1` on windows machine in virtual box, I am getting following error:

duty mode detected

Traceback (most recent call last):
  File "C:\DSS\DSSnet\dss\powerCoord.py", line 73, in <module>
    engine=win32com.client.Dispatch("OpenDSSEngine.DSS")
  File "C:\Python27\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "C:\Python27\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "C:\Python27\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
com_error: (-2147221005, 'Invalid class string', None, None)

I am unable to trace out what is the problem? It would be really helpful if you could write back for a solution.

**Comment by annonch** [comment]
This problem is usually caused by the OpenDSS not having the com port registered on Windows Registry. Firstly, make sure that the engine is registered in the windows registry.
from command line inside the directory of openDSS, and as administrator, C:\Windows\System32\regsvr32.exe OpenDSSEngine.DLL
This is some info I found in the OpenDSS forum: https://sourceforge.net/p/electricdss/discussion/861977/thread/b4ce49b9/
